title: Justin Tay # your name (or website title) here
logo: "/images/myprofilepic.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data driven web developer with diverse background and a passion of analytics.<br>
  I continuously invest in my personal and professional development.<br>
  Since I already got experiences in SQL, I'm currently improving my skills in Data Analytics, Excel, Power BI & Tableau.

  <a href="https://www.linkedin.com/in/justintay05/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
